In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
encoder = nn.Sequential(nn.Linear(10,20), nn.Sigmoid())
decoder = nn.Sequential(nn.Linear(20,10), nn.Sigmoid())
autoencoder = nn.Sequential(encoder, decoder)

In [3]:
input = torch.randn(10)
print(input)
out = encoder(input)
ini = decoder(out)
#print(out)
out1 = autoencoder(input)

tensor([ 1.3442, -1.1335, -0.7935,  0.3739, -0.0136,  0.2514,  0.0747,  0.2241,
         1.9891,  1.9467])


In [4]:
print(out1)

tensor([0.4695, 0.5590, 0.4920, 0.3265, 0.5161, 0.4787, 0.5865, 0.4028, 0.4964,
        0.5040], grad_fn=<SigmoidBackward>)


In [5]:
print(out)

tensor([0.5896, 0.4352, 0.3577, 0.3928, 0.5114, 0.4778, 0.2666, 0.2954, 0.5819,
        0.7567, 0.5047, 0.7899, 0.7774, 0.5405, 0.7053, 0.2440, 0.3734, 0.3845,
        0.4777, 0.7736], grad_fn=<SigmoidBackward>)


In [6]:
print(ini)

tensor([0.4695, 0.5590, 0.4920, 0.3265, 0.5161, 0.4787, 0.5865, 0.4028, 0.4964,
        0.5040], grad_fn=<SigmoidBackward>)


In [7]:
print(input)

tensor([ 1.3442, -1.1335, -0.7935,  0.3739, -0.0136,  0.2514,  0.0747,  0.2241,
         1.9891,  1.9467])
